name: Fernando Teodoro
fullName: Fernando Agustin Teodoro
location: Melbourne, Australia
email: fernandoagustin803@gmail.com
linkedin: https://linkedin.com/in/fernando-agustin-teodoro
github: https://github.com/fteodoro803
